export const recipeTypes = {
  FETCH_INITIAL_SUCCESS: 'FETCH_INITIAL_SUCCESS',
  FETCH_INITIAL_FAILURE: 'FETCH_INITIAL_FAILURE',
  FETCH_CATEGORY_SUCCESS: 'FETCH_CATEGORY_SUCCESS',
  FETCH_CATEGORY_FAILURE: 'FETCH_CATEGORY_FAILURE',  
  FETCH_DETAIL_SUCCESS: 'FETCH_DETAIL_SUCCESS',
  FETCH_DETAIL_FAILURE: 'FETCH_DETAIL_FAILURE',
  SEARCH_RECIPE_SUCCESS: 'SEARCH_RECIPE_SUCCESS',
  SEARCH_RECIPE_FAILURE: 'SEARCH_RECIPE_FAILURE'
}